## V1.1 エンコーディングおよびサニタイゼーションアーキテクチャ

| 章/要件ID | レベル | 要点 | 対応可否 | WebPTでの扱い | 備考 | WSTG番号 | 具体的な攻撃例 | 精査方法(検出とする理由) | 対象のWSTGリンク |
| :---: | :---: | :--- | :---: | :--- | :--- | :--- | :--- | :--- | :--- |
| V1.1.1 | L2 | 入力は一度だけ標準形式にデコード／アンエスケープされ、処理前に行うこと（入力バリデーション後に行わない）。 | 部分対応 | 入力のエンコード経路観察、二重デコードの検出（リクエスト差分／侵入テスト） | 実装確認やログ参照があると確実。 | WSTG-INPV-01 | `%253Cscript%253Ealert(1)%253C/script%253E` を送信し二重デコードで `<script>` が反射実行 | 単一エンコードと二重エンコードの比較で反射挙動差を観察しスクリプト実行を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting |
| V1.1.2 | L2 | 出力エンコーディング／エスケープは最終ステップで行うこと（インタプリタに渡す直前）。 | 部分対応 | 出力のエンコード方法の検証（反射・保存型ペイロードで確認） | ライブラリ自動エスケープの有無はホワイトボックスで評価すると良い。 | WSTG-INPV-02 | 掲示板に `<img src=x onerror=alert(1)>` を保存し表示時に実行されるか検証 | 保存→閲覧で出力時のエスケープ欠如により XSS が成立することを確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/02-Testing_for_Stored_Cross_Site_Scripting |

---

## V1.2 インジェクション防御

| 章/要件ID | レベル | 要点 | 対応可否 | WebPTでの扱い | 備考 | WSTG番号 | 具体的な攻撃例 | 精査方法(検出とする理由) | 対象のWSTGリンク |
| :---: | :---: | :--- | :---: | :--- | :--- | :--- | :--- | :--- | :--- |
| V1.2.1 | L1 | HTML/HTTP/CSS/コメント等、各コンテキストに応じた出力エンコードを行うこと。 | 対応可 | XSS向けペイロードテスト、レスポンスコンテキスト解析 | ブラウザ実行コンテキストで確認可能。 | WSTG-INPV-01 | `"><script>alert(1)</script>` を各入力で反射確認 | 反射位置のコンテキスト（HTML本文/属性/JS）に応じて実行成立を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/01-Testing_for_Reflected_Cross_Site_Scripting |
| V1.2.2 | L1 | 動的URL構築時はコンテキストに応じたエンコードを行い、危険なプロトコルを許可しない。 | 対応可 | URL生成点のパラメータ操作、プロトコルスキーム検証（javascript:, data: 等拒否） | リダイレクト、open-redirect 諸検査で併せて確認。 | WSTG-CLNT-04 | `next=//evil.tld` や `next=javascript:alert(1)` で遷移/実行を誘発 | クライアント側/サーバ側で未検証のリダイレクトや危険スキーム受理を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Client-side_Testing/04-Testing_for_Client-side_URL_Redirect |
| V1.2.3 | L1 | 動的に構築する JS/JSON コンテンツは構造を破壊しないようにエンコードすること（JS/JSON 注入防止）。 | 対応可 | JSON/JS を出力するエンドポイントに対するインジェクションテスト | ブラウザ/解析ツールで確認。 | WSTG-CLNT-02 | JSON値に `";alert(1);//` を混入させスクリプト注入を狙う | 生成されたスクリプト/テンプレートの構文崩壊や実行発火を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/11-Client-side_Testing/02-Testing_for_JavaScript_Execution |
| V1.2.4 | L1 | DB クエリはパラメータ化／ORM 等で保護し、SQL インジェクションを防ぐこと。 | 対応可 | SQLi ペイロード（盲目含む）、エラーベース／時間差検査 | 一部はホワイトボックス/ログ参照で確証。 | WSTG-INPV-05 | `' OR 1=1--`、`'||pg_sleep(5)||'` 等で抽出/遅延を誘発 | レスポンス差/時間差/エラー情報からクエリ介入の可否を立証 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/05-Testing_for_SQL_Injection |
| V1.2.5 | L1 | OS コマンド呼び出しは適切に保護（パラメータ化やエンコード）されていること。 | 部分対応 | コマンドインジェクションペイロードによる検査（入力→外部影響確認） | 実行環境や出力確認が必要なため限定的。 | WSTG-INPV-12 | `;sleep 5;#`、`& ping -c 1 attacker` 等で時間/外部呼出し検証 | 応答遅延や外部監視(OOB)でコマンド実行の事実を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/12-Testing_for_Command_Injection |
| V1.2.6 | L2 | LDAP インジェクション対策が施されていること。 | 部分対応 | LDAP クエリに関する入力を用いた検査（LDAP ベースの機能が存在する場合） | LDAP サービス利用有無に依存。 | WSTG-INPV-06 | `*)(|(uid=*))` などフィルタ合成で認証回避 | エラー/結果件数の異常増加によりフィルタ注入成立を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/06-Testing_for_LDAP_Injection |
| V1.2.7 | L2 | XPath/XQuery 等に対するパラメータ化・保護を行うこと。 | 部分対応 | XML/XPath を利用する機能に対するペイロード検査 | サービス構成確認が有効。 | WSTG-INPV-09 | `'+or+1=1+or+'` や `] | * | a[1=1]` で照合回避 | 認証/検索結果の不正拡大でXPath注入を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/09-Testing_for_XPath_Injection |
| V1.2.8 | L2 | LaTeX 等外部プロセッサは安全に構成（例: shell-escape 無効）されること。 | 範囲外 | 設定確認を推奨（ドキュメント生成機能が対象の場合は限定検査） | ビルド／環境の確認が必要。 | - | - | - | - |
| V1.2.9 | L2 | 正規表現内の特殊文字を適切にエスケープして誤解釈を防ぐこと。 | 部分対応 | 正規表現処理を伴う入力処理の挙動確認（ReDoS 予兆の検査） | ReDoS は負荷試験注意。 | WSTG-INPV-11 | 入力に `.*$` や 改行/バックスラッシュを混入しパターン逸脱 | サーバ側の意図しないマッチ/拒否でコード/式解釈介入を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/11-Testing_for_Code_Injection |
| V1.2.10 | L3 | CSV／スプレッドシートインジェクション対策（RFC4180 準拠、先頭特殊文字をクオート等）。 | 部分対応 | CSV エクスポート機能に対するフィールド先頭文字検査（エクスポート結果の検査） | エクスポート確認はステージングで慎重に実施。 | WSTG-BUSL-09 | `=HYPERLINK("http://attacker","X")` や `=CMD|' /C calc'!A0` をフィールド先頭に挿入 | エクスポート後に表計算ソフトで式評価される事実を確認 | https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/10-Business_Logic_Testing/09-Testing_for_Upload_of_Malicious_Files |